"use client";

import { type ReactNode, useEffect, useState } from "react";
import { ArrowLeft, Building2, ClipboardList, GraduationCap, HandHeart, Loader2, ShieldCheck } from "lucide-react";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";

type Item = { id:number; challengeId?:number; reference?:string; title?:string; location?:string; category?:string; teamName?:string; institution?:string; organization?:string; supportType?:string; status:"pending"|"approved"|"rejected"; createdAt:string };
type Activity = { reports:Item[]; solutions:Item[]; offers:Item[] };

export default function TrackPage(){
  const[data,setData]=useState<Activity|null>(null),[error,setError]=useState("");
  useEffect(()=>{const key=localStorage.getItem("samarthya-device-key");if(!key){setData({reports:[],solutions:[],offers:[]});return}fetch(`/api/my-activity?key=${encodeURIComponent(key)}`,{cache:"no-store"}).then(async response=>{const result=await response.json() as Activity&{error?:string};if(!response.ok)throw new Error(result.error??"Could not load activity.");setData(result)}).catch(err=>setError(err instanceof Error?err.message:"Could not load activity."))},[]);
  return <main className="track-page"><header className="detail-header"><div className="detail-shell"><a href="/"><ArrowLeft/>Home</a><span className="detail-brand"><HandHeart/> समर्थ्य</span></div></header><section className="track-hero"><div className="detail-shell"><span>YOUR DEVICE · PRIVATE VIEW</span><h1>Track your submissions</h1><p>See the review status of reports, student proposals and support offers submitted from this browser.</p><div className="track-privacy"><ShieldCheck/>This page does not require your name or phone number. Activity stays linked only to this browser.</div></div></section><section className="track-content"><div className="detail-shell">{error?<div className="admin-error">{error}</div>:!data?<div className="track-loading"><Loader2 className="spin"/>Loading your activity…</div>:<Tabs defaultValue="reports"><TabsList className="workspace-tabs"><TabsTrigger value="reports">Reports ({data.reports.length})</TabsTrigger><TabsTrigger value="solutions">Solutions ({data.solutions.length})</TabsTrigger><TabsTrigger value="offers">Offers ({data.offers.length})</TabsTrigger></TabsList><TabsContent value="reports"><ActivityList items={data.reports} icon={<ClipboardList/>} empty="No reports submitted from this browser."/></TabsContent><TabsContent value="solutions"><ActivityList items={data.solutions} icon={<GraduationCap/>} empty="No student solutions submitted from this browser."/></TabsContent><TabsContent value="offers"><ActivityList items={data.offers} icon={<Building2/>} empty="No industry offers submitted from this browser."/></TabsContent></Tabs>}</div></section></main>
}

function ActivityList({items,icon,empty}:{items:Item[];icon:ReactNode;empty:string}){if(!items.length)return <div className="track-empty">{icon}<strong>{empty}</strong><a href="/">Explore challenges</a></div>;return <div className="activity-list">{items.map(item=><article key={item.id}><span className="activity-icon">{icon}</span><div><small>{item.reference??`Challenge #${item.challengeId}`} · {new Date(item.createdAt).toLocaleDateString()}</small><h2>{item.title??item.teamName??item.organization}</h2><p>{item.location??item.institution??item.supportType}</p></div><span className={`status status-${item.status}`}>{item.status}</span>{item.status==="approved"&&item.challengeId&&<a href={`/challenges/${item.challengeId}`}>Open</a>}{item.status==="approved"&&item.reference&&<a href={`/challenges/${item.id}`}>Open</a>}</article>)}</div>}
