"use client";

import { FormEvent, ReactNode, useEffect, useState } from "react";
import { ArrowLeft, BadgeCheck, BriefcaseBusiness, Building2, CalendarDays, CheckCircle2, GraduationCap, HandHeart, Lightbulb, Loader2, MapPin, Send, Users } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";

type Data = {
  challenge: { id:number; reference:string; title:string; description:string; location:string; category:string; supportCount:number; teams:number; urgency:string; latitude?:string|null; longitude?:string|null; photoUrl?:string|null; createdAt:string };
  solutions: { id:number; teamName:string; institution:string; summary:string; approach:string; memberCount:number; createdAt:string }[];
  offers: { id:number; organization:string; supportType:string; message:string; createdAt:string }[];
  updates: { id:number; title:string; content:string; stage:string; createdAt:string }[];
};
function key(){const current=localStorage.getItem("samarthya-device-key");if(current)return current;const made=`${crypto.randomUUID()}-${Date.now().toString(36)}`;localStorage.setItem("samarthya-device-key",made);return made}

export default function ChallengeWorkspace({ challengeId }: { challengeId: string }) {
  const [data,setData]=useState<Data|null>(null),[error,setError]=useState("");
  async function load(){try{const response=await fetch(`/api/challenges/${challengeId}`,{cache:"no-store"});const result=await response.json() as Data&{error?:string};if(!response.ok)throw new Error(result.error??"Challenge not found.");setData(result)}catch(err){setError(err instanceof Error?err.message:"Could not load challenge.")}}
  useEffect(()=>{void load()},[challengeId]);
  if(error)return <main className="detail-state"><div><h1>Challenge unavailable</h1><p>{error}</p><a href="/">Return home</a></div></main>;
  if(!data)return <main className="detail-state"><Loader2 className="spin"/><p>Loading collaboration workspace…</p></main>;
  const {challenge}=data;
  return <main className="detail-page">
    <header className="detail-header"><div className="detail-shell"><a href="/"><ArrowLeft/>All challenges</a><span className="detail-brand"><HandHeart/> समर्थ्य</span></div></header>
    <section className="detail-hero"><div className="detail-shell detail-hero-grid"><div><div className="detail-kicker"><BadgeCheck/> VERIFIED · {challenge.reference}</div><span className="detail-category">{challenge.category}</span><h1>{challenge.title}</h1><p>{challenge.description}</p><div className="detail-facts"><span><MapPin/>{challenge.location}</span><span><Users/>{challenge.teams} solution teams</span><span><HandHeart/>{challenge.supportCount} supporters</span></div>{challenge.latitude&&challenge.longitude&&<a className="map-link" target="_blank" rel="noreferrer" href={`https://www.openstreetmap.org/?mlat=${challenge.latitude}&mlon=${challenge.longitude}#map=14/${challenge.latitude}/${challenge.longitude}`}><MapPin/>View approximate problem area</a>}</div>{challenge.photoUrl?<img className="challenge-photo" src={challenge.photoUrl} alt="Community-submitted evidence for this challenge"/>:<div className="detail-visual"><Lightbulb/><strong>Local need</strong><span>Open for collaborative solutions</span></div>}</div></section>
    <section className="detail-workspace"><div className="detail-shell"><Tabs defaultValue="solutions"><TabsList className="workspace-tabs"><TabsTrigger value="solutions">Student solutions ({data.solutions.length})</TabsTrigger><TabsTrigger value="offers">Industry support ({data.offers.length})</TabsTrigger><TabsTrigger value="updates">Progress updates ({data.updates.length})</TabsTrigger></TabsList>
      <TabsContent value="solutions"><div className="workspace-heading"><div><h2>Student teams and solutions</h2><p>Universities can propose practical approaches for this verified challenge.</p></div><SolutionDialog challengeId={challenge.id}/></div><div className="collab-grid">{data.solutions.length?data.solutions.map(s=><article className="collab-card" key={s.id}><div className="collab-icon student"><GraduationCap/></div><span>{s.institution} · {s.memberCount} members</span><h3>{s.teamName}</h3><p>{s.summary}</p><details><summary>View approach</summary><p>{s.approach}</p></details></article>):<Empty icon={<GraduationCap/>} title="No approved solutions yet" text="Be the first student team to propose one."/>}</div></TabsContent>
      <TabsContent value="offers"><div className="workspace-heading"><div><h2>Industry and mentor support</h2><p>Organizations can offer expertise, equipment, pilots, mentorship, or funding pledges.</p></div><OfferDialog challengeId={challenge.id}/></div><div className="collab-grid">{data.offers.length?data.offers.map(o=><article className="collab-card" key={o.id}><div className="collab-icon industry"><Building2/></div><span>{o.supportType}</span><h3>{o.organization}</h3><p>{o.message}</p></article>):<Empty icon={<BriefcaseBusiness/>} title="No approved offers yet" text="An industry partner can be the first to support this challenge."/>}</div></TabsContent>
      <TabsContent value="updates"><div className="workspace-heading"><div><h2>Progress timeline</h2><p>Verified milestones posted by the platform administrator.</p></div></div><div className="timeline">{data.updates.length?data.updates.map(u=><article key={u.id}><span className="timeline-dot"/><div><small>{u.stage} · {new Date(u.createdAt).toLocaleDateString()}</small><h3>{u.title}</h3><p>{u.content}</p></div></article>):<Empty icon={<CalendarDays/>} title="No progress updates yet" text="Updates will appear when work begins."/>}</div></TabsContent>
    </Tabs></div></section>
  </main>;
}

function Empty({icon,title,text}:{icon:ReactNode;title:string;text:string}){return <div className="collab-empty"><span>{icon}</span><strong>{title}</strong><p>{text}</p></div>}
function SolutionDialog({challengeId}:{challengeId:number}){const[open,setOpen]=useState(false);return <Dialog open={open} onOpenChange={setOpen}><DialogTrigger asChild><Button><GraduationCap/>Propose a solution</Button></DialogTrigger><DialogContent className="collab-dialog"><DialogHeader><DialogTitle>Submit your team’s solution</DialogTitle><DialogDescription>Keep it practical. The admin will review it before publication.</DialogDescription></DialogHeader><CollabForm kind="solution" challengeId={challengeId} done={()=>setOpen(false)}/></DialogContent></Dialog>}
function OfferDialog({challengeId}:{challengeId:number}){const[open,setOpen]=useState(false);return <Dialog open={open} onOpenChange={setOpen}><DialogTrigger asChild><Button className="industry-button"><Building2/>Offer support</Button></DialogTrigger><DialogContent className="collab-dialog"><DialogHeader><DialogTitle>Offer industry or mentor support</DialogTitle><DialogDescription>This records a non-binding offer for admin review. No payment is processed.</DialogDescription></DialogHeader><CollabForm kind="offer" challengeId={challengeId} done={()=>setOpen(false)}/></DialogContent></Dialog>}
function CollabForm({kind,challengeId,done}:{kind:"solution"|"offer";challengeId:number;done:()=>void}){
  const[fields,setFields]=useState<Record<string,string>>({}),[type,setType]=useState(""),[sending,setSending]=useState(false),[message,setMessage]=useState("");const update=(name:string,value:string)=>setFields(f=>({...f,[name]:value}));
  async function submit(e:FormEvent){e.preventDefault();setSending(true);setMessage("");const body=kind==="solution"?{teamName:fields.teamName,institution:fields.institution,summary:fields.summary,approach:fields.approach,memberCount:Number(fields.memberCount),submitterKey:key()}:{organization:fields.organization,supportType:type,message:fields.message,submitterKey:key()};try{const response=await fetch(`/api/challenges/${challengeId}/${kind==="solution"?"solutions":"offers"}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});const result=await response.json() as{error?:string};if(!response.ok)throw new Error(result.error??"Submission failed.");setMessage("Saved! It is waiting for admin approval.");setTimeout(done,1200)}catch(err){setMessage(err instanceof Error?err.message:"Submission failed.")}finally{setSending(false)}}
  return <form className="collab-form" onSubmit={submit}>{kind==="solution"?<><div className="form-row"><label>Team name<Input required maxLength={80} onChange={e=>update("teamName",e.target.value)}/></label><label>University / institution<Input required maxLength={120} onChange={e=>update("institution",e.target.value)}/></label></div><div className="form-row"><label>Number of members<Input type="number" min={1} max={12} required onChange={e=>update("memberCount",e.target.value)}/></label><label>One-line solution<Input required minLength={20} maxLength={500} onChange={e=>update("summary",e.target.value)}/></label></div><label>How will your solution work?<textarea required minLength={30} maxLength={1500} onChange={e=>update("approach",e.target.value)}/></label></>:<><label>Organization / mentor group<Input required maxLength={120} onChange={e=>update("organization",e.target.value)}/></label><label>Support type<Select value={type} onValueChange={setType} required><SelectTrigger className="w-full"><SelectValue placeholder="Choose support"/></SelectTrigger><SelectContent>{["Mentorship","Equipment","Pilot access","Technical expertise","Funding pledge","Other"].map(v=><SelectItem key={v} value={v}>{v}</SelectItem>)}</SelectContent></Select></label><label>What can you offer?<textarea required minLength={20} maxLength={1000} onChange={e=>update("message",e.target.value)}/></label></>}{message&&<p className={message.startsWith("Saved")?"form-success":"form-error"}>{message}</p>}<p className="privacy-note"><CheckCircle2/>Do not include private contact details. Admin coordination comes later.</p><Button disabled={sending||(kind==="offer"&&!type)} type="submit">{sending?<Loader2 className="spin"/>:<Send/>}{sending?"Saving…":"Submit for review"}</Button></form>
}
