"use client";

import { FormEvent, useEffect, useState } from "react";
import { ArrowRight, Building2, CheckCircle2, Clock3, GraduationCap, HandHeart, Loader2, LogOut, MapPin, School, ShieldAlert, Sparkles, Users } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";

type User = { id:number; name:string; email:string; role:"student"|"university"|"industry"; organization:string; isVerified:boolean };
type Challenge = { id:number; title:string; location:string; category:string; teams:number; supportCount:number };
type WorkItem = { id:number; challengeId:number; challengeTitle:string; status?:string; teamName?:string; summary?:string; supportType?:string; message?:string; mentorName?:string; note?:string };
type Data = { user:User; challenges:Challenge[]; proposals?:WorkItem[]; offers?:WorkItem[]; mentorships?:WorkItem[] };

export default function DashboardPage() {
  const [data,setData]=useState<Data|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState("");
  const [challengeId,setChallengeId]=useState(""),[mentorName,setMentorName]=useState(""),[note,setNote]=useState(""),[saving,setSaving]=useState(false);
  async function load(){setLoading(true);try{const response=await fetch("/api/dashboard",{cache:"no-store"});if(response.status===401){window.location.href="/account";return}const result=await response.json() as Data&{error?:string};if(!response.ok)throw new Error(result.error??"Could not load dashboard.");setData(result)}catch(err){setError(err instanceof Error?err.message:"Could not load dashboard.")}finally{setLoading(false)}}
  useEffect(()=>{void load()},[]);
  async function logout(){await fetch("/api/auth/session",{method:"DELETE"});window.location.href="/"}
  async function mentor(event:FormEvent){event.preventDefault();setSaving(true);setError("");try{const response=await fetch("/api/dashboard",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({challengeId:Number(challengeId),mentorName,note})});const result=await response.json() as{error?:string};if(!response.ok)throw new Error(result.error??"Could not assign mentor.");setChallengeId("");setMentorName("");setNote("");await load()}catch(err){setError(err instanceof Error?err.message:"Could not assign mentor.")}finally{setSaving(false)}}
  if(loading)return <main className="dashboard-state"><Loader2 className="spin"/><p>Preparing your workspace…</p></main>;
  if(!data)return <main className="dashboard-state"><ShieldAlert/><h1>Dashboard unavailable</h1><p>{error}</p><a href="/account">Return to sign in</a></main>;
  const {user}=data;const RoleIcon=user.role==="student"?GraduationCap:user.role==="university"?School:Building2;
  const title=user.role==="student"?"Student solution studio":user.role==="university"?"University partnership hub":"Industry impact desk";
  const items=user.role==="industry"?data.offers??[]:data.proposals??[];
  return <main className={`dashboard-page role-${user.role}`}><header className="dashboard-header"><div className="dashboard-shell"><a className="dashboard-brand" href="/"><HandHeart/> समर्थ्य <small>Samarthya</small></a><div><span>{user.name}</span><Button variant="outline" size="sm" onClick={logout}><LogOut/> Sign out</Button></div></div></header><div className="dashboard-shell dashboard-content">
    <section className="dashboard-welcome"><div><span className="dashboard-role"><RoleIcon/>{user.role}</span><h1>{title}</h1><p>{user.organization} · {user.email}</p></div><div className={user.isVerified?"verified-card":"waiting-card"}>{user.isVerified?<CheckCircle2/>:<Clock3/>}<div><strong>{user.isVerified?"Verified profile":"Verification pending"}</strong><small>{user.isVerified?"Your role-based tools are active.":"Admin will review your organization profile."}</small></div></div></section>
    <section className="dashboard-stats"><article><Sparkles/><div><strong>{items.length}</strong><span>{user.role==="industry"?"support offers":"solution proposals"}</span></div></article><article><Users/><div><strong>{data.challenges.length}</strong><span>open challenges</span></div></article>{user.role==="university"&&<article><School/><div><strong>{data.mentorships?.length??0}</strong><span>mentorships</span></div></article>}</section>
    {error&&<p className="dashboard-error">{error}</p>}
    {user.role==="university"&&<section className="dashboard-panel"><div className="dashboard-panel-heading"><div><span>FACULTY ACTION</span><h2>Assign a mentor</h2></div><p>Connect a faculty expert with an approved community challenge.</p></div><form className="mentor-form" onSubmit={mentor}><label>Challenge<Select required value={challengeId} onValueChange={setChallengeId}><SelectTrigger><SelectValue placeholder="Choose an approved challenge"/></SelectTrigger><SelectContent>{data.challenges.map(c=><SelectItem key={c.id} value={String(c.id)}>{c.title}</SelectItem>)}</SelectContent></Select></label><label>Mentor name<Input required minLength={2} maxLength={100} value={mentorName} onChange={e=>setMentorName(e.target.value)} placeholder="Faculty mentor"/></label><label className="mentor-note">Mentorship plan<textarea required minLength={10} maxLength={500} value={note} onChange={e=>setNote(e.target.value)} placeholder="How will the mentor guide this team?"/></label><Button disabled={saving||!user.isVerified}>{saving?<Loader2 className="spin"/>:<School/>}{user.isVerified?"Assign mentor":"Verification required"}</Button></form>{(data.mentorships??[]).map(item=><article className="work-row" key={item.id}><School/><div><strong>{item.challengeTitle}</strong><p>{item.mentorName} · {item.note}</p></div></article>)}</section>}
    <section className="dashboard-panel"><div className="dashboard-panel-heading"><div><span>YOUR WORK</span><h2>{user.role==="student"?"Submitted solutions":user.role==="university"?"Student teams from your university":"Support offers"}</h2></div></div><div className="work-list">{items.length?items.map(item=><article className="work-row" key={item.id}>{user.role==="industry"?<Building2/>:<GraduationCap/>}<div><strong>{item.teamName??item.supportType} · {item.challengeTitle}</strong><p>{item.summary??item.message}</p></div>{item.status&&<span className={`status status-${item.status}`}>{item.status}</span>}</article>):<div className="dashboard-empty"><RoleIcon/><strong>No activity yet</strong><p>Open an approved challenge to begin contributing.</p></div>}</div></section>
    <section className="dashboard-panel"><div className="dashboard-panel-heading"><div><span>LIVE OPPORTUNITIES</span><h2>Approved community challenges</h2></div><p>Choose a real need where your skills can create measurable impact.</p></div><div className="opportunity-grid">{data.challenges.map(c=><article key={c.id}><span>{c.category}</span><h3>{c.title}</h3><p><MapPin/> {c.location}</p><div><small>{c.teams} teams · {c.supportCount} supporters</small><a href={`/challenges/${c.id}`}>Open <ArrowRight/></a></div></article>)}</div></section>
  </div></main>;
}
